version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${UID}
    network_mode: host
    environment:
      ROS_IP: ${ROS_IP}
      ROS_MASTER_URI: ${ROS_MASTER_URI}
      ROS_HOSTNAME: ${ROS_HOSTNAME}
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${XAUTHORITY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    user: ${UID_GID}
