#!/usr/bin/env python

import rospy
import sys
from std_msgs.msg import Float64, String
from mr_messages.msg import Speed
from PyQt4 import QtGui, QtCore

PKG = 'pyqt_testing'

NODE = 'send_key_cmd'

PROP_SPEED = 127
RUDDER_SPEED = 40
SAIL_SPEED = 40


class Window(QtGui.QMainWindow):

    def __init__(self):
        self.rc = RosCommands()
        super(Window, self).__init__()
        self.setGeometry(50, 50, 500, 300)
        self.setWindowTitle("manual boat control test")
        self.home()

    def home(self):
        btn = QtGui.QPushButton("Enable manual control", self)
        btn.clicked.connect(self.enable_manual)
        btn.resize(btn.minimumSizeHint())
        btn.move(0,0)
        self.show()

    def enable_manual(self):
        self.rc.pub_manual_cmd("start_manual")

    def keyPressEvent(self, event):

        # SPEED EVENTS
        if event.key() == QtCore.Qt.Key_W and not event.isAutoRepeat():
            self.rc.pub_prop_effort(PROP_SPEED)
        elif event.key() == QtCore.Qt.Key_S and not event.isAutoRepeat():
            self.rc.pub_prop_effort(-PROP_SPEED)

        # RUDDER EVENTS
        elif event.key() == QtCore.Qt.Key_D and not event.isAutoRepeat():
            self.rc.pub_rudder_effort(RUDDER_SPEED)
        elif event.key() == QtCore.Qt.Key_A and not event.isAutoRepeat():
            self.rc.pub_rudder_effort(-RUDDER_SPEED)

        # SAIL EVENTS
        elif event.key() == QtCore.Qt.Key_E and not event.isAutoRepeat():
            self.rc.pub_sail_effort(SAIL_SPEED)
        elif event.key() == QtCore.Qt.Key_Q and not event.isAutoRepeat():
            self.rc.pub_sail_effort(-SAIL_SPEED)

        event.accept()

    def keyReleaseEvent(self, event):

        # SPEED EVENTS
        if event.key() == QtCore.Qt.Key_W and not event.isAutoRepeat():
            self.rc.pub_prop_effort(0)
        elif event.key() == QtCore.Qt.Key_S and not event.isAutoRepeat():
            self.rc.pub_prop_effort(0)

        # RUDDER EVENTS
        elif event.key() == QtCore.Qt.Key_A and not event.isAutoRepeat():
            self.rc.pub_rudder_effort(0)
        elif event.key() == QtCore.Qt.Key_D and not event.isAutoRepeat():
            self.rc.pub_rudder_effort(0)

        # SAIL EVENTS
        elif event.key() == QtCore.Qt.Key_E and not event.isAutoRepeat():
            self.rc.pub_sail_effort(0)
        elif event.key() == QtCore.Qt.Key_Q and not event.isAutoRepeat():
            self.rc.pub_sail_effort(0)

        event.accept()

    def closeEvent(self, event):
        """Stop all motors on close"""
        self.rc.pub_prop_effort(0)
        self.rc.pub_rudder_effort(0)
        self.rc.pub_sail_effort(0)


class RosCommands(object):

    def __init__(self):
        rospy.init_node(NODE, anonymous=True)
        self.speed = Speed()
        self.rudder_effort_pub = rospy.Publisher('manual/cmd_rudder_effort',
                                                 Float64,
                                                 queue_size=10)
        self.prop_effort_pub = rospy.Publisher('manual/cmd_prop_effort',
                                               Float64,
                                               queue_size=10)
        self.sail_effort_pub = rospy.Publisher('manual/cmd_sail_effort',
                                               Float64,
                                               queue_size=10)
        self.mission_cmd_pub = rospy.Publisher('cmd_mission',
                                               String,
                                               queue_size=10)

    def pub_rudder_effort(self, effort):
        self.rudder_effort_pub.publish(effort)

    def pub_prop_effort(self, speed):
        self.speed.time = rospy.Time.now()
        self.speed.speed = speed
        self.prop_effort_pub.publish(self.speed)

    def pub_sail_effort(self, effort):
        self.sail_effort_pub.publish(effort)

    def pub_manual_cmd(self, cmd):
        self.mission_cmd_pub.publish(cmd)


if __name__ == '__main__':
    app = QtGui.QApplication(sys.argv)
    GUI = Window()
    sys.exit(app.exec_())