# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1131, 811)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 741))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(390, 80, 251, 161))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txtHeading = QtWidgets.QLineEdit(self.frame)
        self.txtHeading.setEnabled(True)
        self.txtHeading.setGeometry(QtCore.QRect(200, 10, 41, 20))
        self.txtHeading.setText("")
        self.txtHeading.setReadOnly(True)
        self.txtHeading.setObjectName("txtHeading")
        self.txtWaterSpeed = QtWidgets.QLineEdit(self.frame)
        self.txtWaterSpeed.setEnabled(True)
        self.txtWaterSpeed.setGeometry(QtCore.QRect(200, 100, 41, 20))
        self.txtWaterSpeed.setReadOnly(True)
        self.txtWaterSpeed.setObjectName("txtWaterSpeed")
        self.txtSOG = QtWidgets.QLineEdit(self.frame)
        self.txtSOG.setEnabled(True)
        self.txtSOG.setGeometry(QtCore.QRect(200, 130, 41, 20))
        self.txtSOG.setReadOnly(True)
        self.txtSOG.setObjectName("txtSOG")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 130, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_24 = QtWidgets.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(0, 40, 191, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName("label_24")
        self.txtSailHeading = QtWidgets.QLineEdit(self.frame)
        self.txtSailHeading.setEnabled(True)
        self.txtSailHeading.setGeometry(QtCore.QRect(200, 40, 41, 20))
        self.txtSailHeading.setReadOnly(True)
        self.txtSailHeading.setObjectName("txtSailHeading")
        self.txtDeclination = QtWidgets.QLineEdit(self.frame)
        self.txtDeclination.setEnabled(True)
        self.txtDeclination.setGeometry(QtCore.QRect(200, 70, 41, 20))
        self.txtDeclination.setReadOnly(True)
        self.txtDeclination.setObjectName("txtDeclination")
        self.label_54 = QtWidgets.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(40, 70, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName("label_54")
        self.lblActuatorStatus_3 = QtWidgets.QLabel(self.tab)
        self.lblActuatorStatus_3.setGeometry(QtCore.QRect(400, 250, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_3.setFont(font)
        self.lblActuatorStatus_3.setObjectName("lblActuatorStatus_3")
        self.btnStartManual = QtWidgets.QPushButton(self.tab)
        self.btnStartManual.setGeometry(QtCore.QRect(20, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartManual.setFont(font)
        self.btnStartManual.setObjectName("btnStartManual")
        self.lblActuatorStatus_2 = QtWidgets.QLabel(self.tab)
        self.lblActuatorStatus_2.setGeometry(QtCore.QRect(400, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_2.setFont(font)
        self.lblActuatorStatus_2.setObjectName("lblActuatorStatus_2")
        self.txtConnectionStatus = QtWidgets.QLineEdit(self.tab)
        self.txtConnectionStatus.setGeometry(QtCore.QRect(750, 300, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtConnectionStatus.setFont(font)
        self.txtConnectionStatus.setAutoFillBackground(False)
        self.txtConnectionStatus.setStyleSheet("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txtConnectionStatus.setFrame(False)
        self.txtConnectionStatus.setReadOnly(True)
        self.txtConnectionStatus.setObjectName("txtConnectionStatus")
        self.txtMode = QtWidgets.QLineEdit(self.tab)
        self.txtMode.setGeometry(QtCore.QRect(750, 330, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtMode.setFont(font)
        self.txtMode.setAutoFillBackground(False)
        self.txtMode.setStyleSheet("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txtMode.setFrame(False)
        self.txtMode.setReadOnly(True)
        self.txtMode.setObjectName("txtMode")
        self.lblControl = QtWidgets.QLabel(self.tab)
        self.lblControl.setGeometry(QtCore.QRect(20, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl.setFont(font)
        self.lblControl.setObjectName("lblControl")
        self.frame_3 = QtWidgets.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(750, 80, 201, 161))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.txtBatVoltage = QtWidgets.QLineEdit(self.frame_3)
        self.txtBatVoltage.setEnabled(True)
        self.txtBatVoltage.setGeometry(QtCore.QRect(130, 72, 61, 20))
        self.txtBatVoltage.setReadOnly(True)
        self.txtBatVoltage.setObjectName("txtBatVoltage")
        self.txtCurrentDraw = QtWidgets.QLineEdit(self.frame_3)
        self.txtCurrentDraw.setEnabled(True)
        self.txtCurrentDraw.setGeometry(QtCore.QRect(130, 100, 61, 20))
        self.txtCurrentDraw.setReadOnly(True)
        self.txtCurrentDraw.setObjectName("txtCurrentDraw")
        self.label_13 = QtWidgets.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(32, 72, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(2, 100, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.txtNumSats = QtWidgets.QLineEdit(self.frame_3)
        self.txtNumSats.setEnabled(True)
        self.txtNumSats.setGeometry(QtCore.QRect(130, 130, 61, 20))
        self.txtNumSats.setReadOnly(True)
        self.txtNumSats.setObjectName("txtNumSats")
        self.label_35 = QtWidgets.QLabel(self.frame_3)
        self.label_35.setGeometry(QtCore.QRect(0, 130, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.label_37 = QtWidgets.QLabel(self.frame_3)
        self.label_37.setGeometry(QtCore.QRect(0, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.txtPower = QtWidgets.QLineEdit(self.frame_3)
        self.txtPower.setEnabled(True)
        self.txtPower.setGeometry(QtCore.QRect(130, 40, 61, 20))
        self.txtPower.setText("")
        self.txtPower.setReadOnly(True)
        self.txtPower.setObjectName("txtPower")
        self.label_38 = QtWidgets.QLabel(self.frame_3)
        self.label_38.setGeometry(QtCore.QRect(0, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.txtBatRemaining = QtWidgets.QLineEdit(self.frame_3)
        self.txtBatRemaining.setEnabled(True)
        self.txtBatRemaining.setGeometry(QtCore.QRect(130, 10, 61, 20))
        self.txtBatRemaining.setText("")
        self.txtBatRemaining.setReadOnly(True)
        self.txtBatRemaining.setObjectName("txtBatRemaining")
        self.btnDisableManual = QtWidgets.QPushButton(self.tab)
        self.btnDisableManual.setGeometry(QtCore.QRect(20, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnDisableManual.setFont(font)
        self.btnDisableManual.setObjectName("btnDisableManual")
        self.frame_2 = QtWidgets.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(390, 290, 251, 301))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.txtWindTrue = QtWidgets.QLineEdit(self.frame_2)
        self.txtWindTrue.setEnabled(True)
        self.txtWindTrue.setGeometry(QtCore.QRect(180, 10, 61, 20))
        self.txtWindTrue.setText("")
        self.txtWindTrue.setReadOnly(True)
        self.txtWindTrue.setObjectName("txtWindTrue")
        self.txtTrueWindSpeed = QtWidgets.QLineEdit(self.frame_2)
        self.txtTrueWindSpeed.setEnabled(True)
        self.txtTrueWindSpeed.setGeometry(QtCore.QRect(180, 40, 61, 20))
        self.txtTrueWindSpeed.setReadOnly(True)
        self.txtTrueWindSpeed.setObjectName("txtTrueWindSpeed")
        self.txtDepth = QtWidgets.QLineEdit(self.frame_2)
        self.txtDepth.setEnabled(True)
        self.txtDepth.setGeometry(QtCore.QRect(180, 130, 61, 20))
        self.txtDepth.setReadOnly(True)
        self.txtDepth.setObjectName("txtDepth")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(40, 10, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(0, 40, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(80, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.label_25 = QtWidgets.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(0, 160, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.txtAirTemp = QtWidgets.QLineEdit(self.frame_2)
        self.txtAirTemp.setEnabled(True)
        self.txtAirTemp.setGeometry(QtCore.QRect(180, 160, 61, 20))
        self.txtAirTemp.setReadOnly(True)
        self.txtAirTemp.setObjectName("txtAirTemp")
        self.txtHumid = QtWidgets.QLineEdit(self.frame_2)
        self.txtHumid.setEnabled(True)
        self.txtHumid.setGeometry(QtCore.QRect(180, 220, 61, 20))
        self.txtHumid.setReadOnly(True)
        self.txtHumid.setObjectName("txtHumid")
        self.txtPres = QtWidgets.QLineEdit(self.frame_2)
        self.txtPres.setEnabled(True)
        self.txtPres.setGeometry(QtCore.QRect(180, 250, 61, 20))
        self.txtPres.setReadOnly(True)
        self.txtPres.setObjectName("txtPres")
        self.label_26 = QtWidgets.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(60, 220, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(10, 250, 161, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.label_55 = QtWidgets.QLabel(self.frame_2)
        self.label_55.setGeometry(QtCore.QRect(0, 70, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName("label_55")
        self.txtWindApp = QtWidgets.QLineEdit(self.frame_2)
        self.txtWindApp.setEnabled(True)
        self.txtWindApp.setGeometry(QtCore.QRect(180, 70, 61, 20))
        self.txtWindApp.setText("")
        self.txtWindApp.setReadOnly(True)
        self.txtWindApp.setObjectName("txtWindApp")
        self.txtApptWindSpeed = QtWidgets.QLineEdit(self.frame_2)
        self.txtApptWindSpeed.setEnabled(True)
        self.txtApptWindSpeed.setGeometry(QtCore.QRect(180, 100, 61, 20))
        self.txtApptWindSpeed.setReadOnly(True)
        self.txtApptWindSpeed.setObjectName("txtApptWindSpeed")
        self.label_56 = QtWidgets.QLabel(self.frame_2)
        self.label_56.setGeometry(QtCore.QRect(0, 100, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName("label_56")
        self.txtWaterTemp = QtWidgets.QLineEdit(self.frame_2)
        self.txtWaterTemp.setEnabled(True)
        self.txtWaterTemp.setGeometry(QtCore.QRect(180, 190, 61, 20))
        self.txtWaterTemp.setReadOnly(True)
        self.txtWaterTemp.setObjectName("txtWaterTemp")
        self.label_28 = QtWidgets.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(0, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.lblActuatorStatus_5 = QtWidgets.QLabel(self.tab)
        self.lblActuatorStatus_5.setGeometry(QtCore.QRect(750, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_5.setFont(font)
        self.lblActuatorStatus_5.setObjectName("lblActuatorStatus_5")
        self.lblActuatorStatus_4 = QtWidgets.QLabel(self.tab)
        self.lblActuatorStatus_4.setGeometry(QtCore.QRect(750, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_4.setFont(font)
        self.lblActuatorStatus_4.setObjectName("lblActuatorStatus_4")
        self.txt0x80Status = QtWidgets.QLineEdit(self.tab)
        self.txt0x80Status.setGeometry(QtCore.QRect(750, 380, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt0x80Status.setFont(font)
        self.txt0x80Status.setAutoFillBackground(False)
        self.txt0x80Status.setStyleSheet("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt0x80Status.setFrame(False)
        self.txt0x80Status.setReadOnly(True)
        self.txt0x80Status.setObjectName("txt0x80Status")
        self.txt0x81Status = QtWidgets.QLineEdit(self.tab)
        self.txt0x81Status.setGeometry(QtCore.QRect(750, 410, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt0x81Status.setFont(font)
        self.txt0x81Status.setAutoFillBackground(False)
        self.txt0x81Status.setStyleSheet("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.txt0x81Status.setFrame(False)
        self.txt0x81Status.setReadOnly(True)
        self.txt0x81Status.setObjectName("txt0x81Status")
        self.btnPropOn = QtWidgets.QPushButton(self.tab)
        self.btnPropOn.setGeometry(QtCore.QRect(20, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPropOn.setFont(font)
        self.btnPropOn.setObjectName("btnPropOn")
        self.btnPropOff = QtWidgets.QPushButton(self.tab)
        self.btnPropOff.setGeometry(QtCore.QRect(20, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPropOff.setFont(font)
        self.btnPropOff.setObjectName("btnPropOff")
        self.label_36 = QtWidgets.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(750, 360, 121, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.label_19 = QtWidgets.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(69, 962, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.txtUTC = QtWidgets.QLineEdit(self.tab)
        self.txtUTC.setGeometry(QtCore.QRect(40, 540, 221, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUTC.sizePolicy().hasHeightForWidth())
        self.txtUTC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtUTC.setFont(font)
        self.txtUTC.setText("")
        self.txtUTC.setObjectName("txtUTC")
        self.label_20 = QtWidgets.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(40, 510, 91, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.txtComments = QtWidgets.QTextEdit(self.tab)
        self.txtComments.setGeometry(QtCore.QRect(40, 610, 271, 70))
        self.txtComments.setObjectName("txtComments")
        self.label_21 = QtWidgets.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(40, 580, 91, 20))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans Mono")
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.frame_5 = QtWidgets.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(750, 490, 251, 100))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.txtState = QtWidgets.QLineEdit(self.frame_5)
        self.txtState.setEnabled(True)
        self.txtState.setGeometry(QtCore.QRect(90, 20, 141, 21))
        self.txtState.setReadOnly(True)
        self.txtState.setObjectName("txtState")
        self.txtSubstate = QtWidgets.QLineEdit(self.frame_5)
        self.txtSubstate.setEnabled(True)
        self.txtSubstate.setGeometry(QtCore.QRect(90, 60, 141, 21))
        self.txtSubstate.setReadOnly(True)
        self.txtSubstate.setObjectName("txtSubstate")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(-20, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(-50, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName("label_23")
        self.lblActuatorStatus_6 = QtWidgets.QLabel(self.tab)
        self.lblActuatorStatus_6.setGeometry(QtCore.QRect(750, 440, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_6.setFont(font)
        self.lblActuatorStatus_6.setObjectName("lblActuatorStatus_6")
        self.btnAutoSail = QtWidgets.QPushButton(self.tab)
        self.btnAutoSail.setGeometry(QtCore.QRect(20, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAutoSail.setFont(font)
        self.btnAutoSail.setObjectName("btnAutoSail")
        self.btnAutoSailDisable = QtWidgets.QPushButton(self.tab)
        self.btnAutoSailDisable.setGeometry(QtCore.QRect(20, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAutoSailDisable.setFont(font)
        self.btnAutoSailDisable.setObjectName("btnAutoSailDisable")
        self.sailCtrlGroup = QtWidgets.QWidget(self.tab)
        self.sailCtrlGroup.setEnabled(True)
        self.sailCtrlGroup.setGeometry(QtCore.QRect(10, 320, 321, 161))
        self.sailCtrlGroup.setObjectName("sailCtrlGroup")
        self.label_16 = QtWidgets.QLabel(self.sailCtrlGroup)
        self.label_16.setGeometry(QtCore.QRect(20, 10, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.layoutWidget_2 = QtWidgets.QWidget(self.sailCtrlGroup)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 30, 211, 41))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txtDesSail = QtWidgets.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesSail.sizePolicy().hasHeightForWidth())
        self.txtDesSail.setSizePolicy(sizePolicy)
        self.txtDesSail.setObjectName("txtDesSail")
        self.horizontalLayout_2.addWidget(self.txtDesSail)
        self.btnDesSail = QtWidgets.QPushButton(self.layoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesSail.sizePolicy().hasHeightForWidth())
        self.btnDesSail.setSizePolicy(sizePolicy)
        self.btnDesSail.setStyleSheet("")
        self.btnDesSail.setObjectName("btnDesSail")
        self.horizontalLayout_2.addWidget(self.btnDesSail)
        self.label_18 = QtWidgets.QLabel(self.sailCtrlGroup)
        self.label_18.setGeometry(QtCore.QRect(20, 80, 151, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.layoutWidget_4 = QtWidgets.QWidget(self.sailCtrlGroup)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 110, 211, 41))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txtDesSailAngle = QtWidgets.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesSailAngle.sizePolicy().hasHeightForWidth())
        self.txtDesSailAngle.setSizePolicy(sizePolicy)
        self.txtDesSailAngle.setObjectName("txtDesSailAngle")
        self.horizontalLayout_4.addWidget(self.txtDesSailAngle)
        self.btnDesSailAngle = QtWidgets.QPushButton(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesSailAngle.sizePolicy().hasHeightForWidth())
        self.btnDesSailAngle.setSizePolicy(sizePolicy)
        self.btnDesSailAngle.setStyleSheet("")
        self.btnDesSailAngle.setObjectName("btnDesSailAngle")
        self.horizontalLayout_4.addWidget(self.btnDesSailAngle)
        self.layoutWidget = QtWidgets.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 210, 211, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.txtDesHeading = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesHeading.sizePolicy().hasHeightForWidth())
        self.txtDesHeading.setSizePolicy(sizePolicy)
        self.txtDesHeading.setObjectName("txtDesHeading")
        self.horizontalLayout.addWidget(self.txtDesHeading)
        self.btnDesHeading = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesHeading.sizePolicy().hasHeightForWidth())
        self.btnDesHeading.setSizePolicy(sizePolicy)
        self.btnDesHeading.setStyleSheet("")
        self.btnDesHeading.setObjectName("btnDesHeading")
        self.horizontalLayout.addWidget(self.btnDesHeading)
        self.label_15 = QtWidgets.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(30, 190, 131, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(20, 280, 211, 41))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.txtDesROT = QtWidgets.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesROT.sizePolicy().hasHeightForWidth())
        self.txtDesROT.setSizePolicy(sizePolicy)
        self.txtDesROT.setObjectName("txtDesROT")
        self.horizontalLayout_3.addWidget(self.txtDesROT)
        self.btnDesROT = QtWidgets.QPushButton(self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesROT.sizePolicy().hasHeightForWidth())
        self.btnDesROT.setSizePolicy(sizePolicy)
        self.btnDesROT.setStyleSheet("")
        self.btnDesROT.setObjectName("btnDesROT")
        self.horizontalLayout_3.addWidget(self.btnDesROT)
        self.label_17 = QtWidgets.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(30, 260, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.sailCtrlGroup.raise_()
        self.frame.raise_()
        self.lblActuatorStatus_3.raise_()
        self.btnStartManual.raise_()
        self.lblActuatorStatus_2.raise_()
        self.txtConnectionStatus.raise_()
        self.txtMode.raise_()
        self.lblControl.raise_()
        self.frame_3.raise_()
        self.btnDisableManual.raise_()
        self.frame_2.raise_()
        self.lblActuatorStatus_5.raise_()
        self.lblActuatorStatus_4.raise_()
        self.txt0x80Status.raise_()
        self.txt0x81Status.raise_()
        self.btnPropOn.raise_()
        self.btnPropOff.raise_()
        self.label_36.raise_()
        self.label_19.raise_()
        self.txtUTC.raise_()
        self.label_20.raise_()
        self.txtComments.raise_()
        self.label_21.raise_()
        self.frame_5.raise_()
        self.lblActuatorStatus_6.raise_()
        self.btnAutoSail.raise_()
        self.btnAutoSailDisable.raise_()
        self.layoutWidget.raise_()
        self.label_15.raise_()
        self.layoutWidget_3.raise_()
        self.label_17.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.lblControl_2 = QtWidgets.QLabel(self.tab_2)
        self.lblControl_2.setEnabled(False)
        self.lblControl_2.setGeometry(QtCore.QRect(20, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl_2.setFont(font)
        self.lblControl_2.setObjectName("lblControl_2")
        self.frame_4 = QtWidgets.QFrame(self.tab_2)
        self.frame_4.setEnabled(False)
        self.frame_4.setGeometry(QtCore.QRect(20, 70, 166, 100))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.txtRudderSpeed = QtWidgets.QLineEdit(self.frame_4)
        self.txtRudderSpeed.setEnabled(False)
        self.txtRudderSpeed.setGeometry(QtCore.QRect(90, 12, 61, 20))
        self.txtRudderSpeed.setReadOnly(True)
        self.txtRudderSpeed.setObjectName("txtRudderSpeed")
        self.txtSailSpeed = QtWidgets.QLineEdit(self.frame_4)
        self.txtSailSpeed.setEnabled(False)
        self.txtSailSpeed.setGeometry(QtCore.QRect(90, 40, 61, 20))
        self.txtSailSpeed.setReadOnly(True)
        self.txtSailSpeed.setObjectName("txtSailSpeed")
        self.txtPropSpeed = QtWidgets.QLineEdit(self.frame_4)
        self.txtPropSpeed.setEnabled(False)
        self.txtPropSpeed.setGeometry(QtCore.QRect(90, 68, 61, 20))
        self.txtPropSpeed.setReadOnly(True)
        self.txtPropSpeed.setObjectName("txtPropSpeed")
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(12, 12, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(2, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(12, 68, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.lblControl_3 = QtWidgets.QLabel(self.tab_2)
        self.lblControl_3.setGeometry(QtCore.QRect(20, 210, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl_3.setFont(font)
        self.lblControl_3.setObjectName("lblControl_3")
        self.btnEnablePIDTuning = QtWidgets.QPushButton(self.tab_2)
        self.btnEnablePIDTuning.setGeometry(QtCore.QRect(30, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnablePIDTuning.setFont(font)
        self.btnEnablePIDTuning.setObjectName("btnEnablePIDTuning")
        self.txtEffort = QtWidgets.QLineEdit(self.tab_2)
        self.txtEffort.setEnabled(False)
        self.txtEffort.setGeometry(QtCore.QRect(310, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtEffort.setFont(font)
        self.txtEffort.setStyleSheet("border: 1px solid transparent;\n"
"background: transparent;")
        self.txtEffort.setReadOnly(True)
        self.txtEffort.setObjectName("txtEffort")
        self.txtIInput = QtWidgets.QLineEdit(self.tab_2)
        self.txtIInput.setGeometry(QtCore.QRect(60, 330, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtIInput.sizePolicy().hasHeightForWidth())
        self.txtIInput.setSizePolicy(sizePolicy)
        self.txtIInput.setObjectName("txtIInput")
        self.txtDInput = QtWidgets.QLineEdit(self.tab_2)
        self.txtDInput.setGeometry(QtCore.QRect(60, 360, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDInput.sizePolicy().hasHeightForWidth())
        self.txtDInput.setSizePolicy(sizePolicy)
        self.txtDInput.setObjectName("txtDInput")
        self.lblEffort = QtWidgets.QLabel(self.tab_2)
        self.lblEffort.setEnabled(False)
        self.lblEffort.setGeometry(QtCore.QRect(210, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblEffort.setFont(font)
        self.lblEffort.setObjectName("lblEffort")
        self.txtROT = QtWidgets.QLineEdit(self.tab_2)
        self.txtROT.setEnabled(False)
        self.txtROT.setGeometry(QtCore.QRect(310, 350, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtROT.setFont(font)
        self.txtROT.setStyleSheet("border: 1px solid transparent;\n"
"background: transparent;")
        self.txtROT.setReadOnly(True)
        self.txtROT.setObjectName("txtROT")
        self.txtPInput = QtWidgets.QLineEdit(self.tab_2)
        self.txtPInput.setGeometry(QtCore.QRect(60, 300, 41, 20))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPInput.sizePolicy().hasHeightForWidth())
        self.txtPInput.setSizePolicy(sizePolicy)
        self.txtPInput.setObjectName("txtPInput")
        self.lblI = QtWidgets.QLabel(self.tab_2)
        self.lblI.setGeometry(QtCore.QRect(30, 330, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblI.setFont(font)
        self.lblI.setObjectName("lblI")
        self.lblROT = QtWidgets.QLabel(self.tab_2)
        self.lblROT.setEnabled(False)
        self.lblROT.setGeometry(QtCore.QRect(210, 350, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblROT.setFont(font)
        self.lblROT.setObjectName("lblROT")
        self.lblD = QtWidgets.QLabel(self.tab_2)
        self.lblD.setGeometry(QtCore.QRect(30, 360, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblD.setFont(font)
        self.lblD.setObjectName("lblD")
        self.txtError = QtWidgets.QLineEdit(self.tab_2)
        self.txtError.setEnabled(False)
        self.txtError.setGeometry(QtCore.QRect(310, 320, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtError.setFont(font)
        self.txtError.setStyleSheet("border: 1px solid transparent;\n"
"background: transparent;")
        self.txtError.setReadOnly(True)
        self.txtError.setObjectName("txtError")
        self.lblP = QtWidgets.QLabel(self.tab_2)
        self.lblP.setGeometry(QtCore.QRect(30, 300, 16, 21))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblP.setFont(font)
        self.lblP.setObjectName("lblP")
        self.lblError = QtWidgets.QLabel(self.tab_2)
        self.lblError.setEnabled(False)
        self.lblError.setGeometry(QtCore.QRect(210, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblError.setFont(font)
        self.lblError.setObjectName("lblError")
        self.btnSetIntegral = QtWidgets.QPushButton(self.tab_2)
        self.btnSetIntegral.setGeometry(QtCore.QRect(110, 330, 41, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetIntegral.sizePolicy().hasHeightForWidth())
        self.btnSetIntegral.setSizePolicy(sizePolicy)
        self.btnSetIntegral.setStyleSheet("")
        self.btnSetIntegral.setObjectName("btnSetIntegral")
        self.tabWidget.addTab(self.tab_2, "")
        self.btnStop = QtWidgets.QPushButton(self.centralwidget)
        self.btnStop.setEnabled(True)
        self.btnStop.setGeometry(QtCore.QRect(10, 770, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Liberation Mono")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet("QPushButton {color: red;}\n"
"")
        self.btnStop.setObjectName("btnStop")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Boat Heading true (deg):"))
        self.label_2.setText(_translate("MainWindow", "Water speed (km/h):"))
        self.label_6.setText(_translate("MainWindow", "SOG (km/h):"))
        self.label_24.setText(_translate("MainWindow", "Sail Heading true (deg):"))
        self.label_54.setText(_translate("MainWindow", "Declination (deg):"))
        self.lblActuatorStatus_3.setText(_translate("MainWindow", "Environment"))
        self.btnStartManual.setText(_translate("MainWindow", "Enable manual"))
        self.lblActuatorStatus_2.setText(_translate("MainWindow", "NAV Info"))
        self.txtConnectionStatus.setText(_translate("MainWindow", "DISCONNECTED"))
        self.txtMode.setText(_translate("MainWindow", "MANUAL DISABLED"))
        self.lblControl.setText(_translate("MainWindow", "Control"))
        self.label_13.setText(_translate("MainWindow", "Bat Voltage"))
        self.label_14.setText(_translate("MainWindow", "Current draw[A]"))
        self.label_35.setText(_translate("MainWindow", "Sats in view"))
        self.label_37.setText(_translate("MainWindow", "Power usage[W]"))
        self.label_38.setText(_translate("MainWindow", "Power level (%)"))
        self.btnDisableManual.setText(_translate("MainWindow", "Disable manual"))
        self.label_10.setText(_translate("MainWindow", "True wind(deg):"))
        self.label_11.setText(_translate("MainWindow", "True wind speed(km/h):"))
        self.label_12.setText(_translate("MainWindow", "Depth (m):"))
        self.label_25.setText(_translate("MainWindow", "Air Temperature(C):"))
        self.label_26.setText(_translate("MainWindow", "Humidity (%):"))
        self.label_27.setText(_translate("MainWindow", "Air Pressure (mbar):"))
        self.label_55.setText(_translate("MainWindow", "Apparent wind(deg):"))
        self.label_56.setText(_translate("MainWindow", "Appt wind speed(km/h):"))
        self.label_28.setText(_translate("MainWindow", "Water Temperature(C):"))
        self.lblActuatorStatus_5.setText(_translate("MainWindow", "Status"))
        self.lblActuatorStatus_4.setText(_translate("MainWindow", "Stats"))
        self.txt0x80Status.setText(_translate("MainWindow", "0x80 No status received"))
        self.txt0x81Status.setText(_translate("MainWindow", "0x81 No status received"))
        self.btnPropOn.setText(_translate("MainWindow", "Prop ON"))
        self.btnPropOff.setText(_translate("MainWindow", "Prop OFF"))
        self.label_36.setText(_translate("MainWindow", "Roboclaws"))
        self.label_19.setText(_translate("MainWindow", "Desired sail angle:"))
        self.label_20.setText(_translate("MainWindow", "UTC Time"))
        self.label_21.setText(_translate("MainWindow", "Comments"))
        self.label_22.setText(_translate("MainWindow", "State :"))
        self.label_23.setText(_translate("MainWindow", "Substate :"))
        self.lblActuatorStatus_6.setText(_translate("MainWindow", "Boat State"))
        self.btnAutoSail.setText(_translate("MainWindow", "Auto sail"))
        self.btnAutoSailDisable.setText(_translate("MainWindow", "Disable auto sail"))
        self.label_16.setText(_translate("MainWindow", "Desired sail heading:"))
        self.btnDesSail.setText(_translate("MainWindow", "SET"))
        self.label_18.setText(_translate("MainWindow", "Desired sail angle:"))
        self.btnDesSailAngle.setText(_translate("MainWindow", "SET"))
        self.btnDesHeading.setText(_translate("MainWindow", "SET"))
        self.label_15.setText(_translate("MainWindow", "Desired heading:"))
        self.btnDesROT.setText(_translate("MainWindow", "SET"))
        self.label_17.setText(_translate("MainWindow", "Desired Rate of Turn "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Overview"))
        self.lblControl_2.setText(_translate("MainWindow", "Set actuator speeds"))
        self.label_7.setText(_translate("MainWindow", "Rudder"))
        self.label_8.setText(_translate("MainWindow", "Sail"))
        self.label_9.setText(_translate("MainWindow", "Prop"))
        self.lblControl_3.setText(_translate("MainWindow", "PID tuning"))
        self.btnEnablePIDTuning.setText(_translate("MainWindow", "Enable"))
        self.txtEffort.setText(_translate("MainWindow", "-99"))
        self.lblEffort.setText(_translate("MainWindow", "Effort"))
        self.txtROT.setText(_translate("MainWindow", "-99"))
        self.lblI.setText(_translate("MainWindow", "I"))
        self.lblROT.setText(_translate("MainWindow", "ROT"))
        self.lblD.setText(_translate("MainWindow", "D"))
        self.txtError.setText(_translate("MainWindow", "-99"))
        self.lblP.setText(_translate("MainWindow", "P"))
        self.lblError.setText(_translate("MainWindow", "Error"))
        self.btnSetIntegral.setText(_translate("MainWindow", "Set"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings"))
        self.btnStop.setText(_translate("MainWindow", "STOP"))
