# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1131, 811)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 741))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(390, 80, 251, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.txtHeading = QtGui.QLineEdit(self.frame)
        self.txtHeading.setEnabled(True)
        self.txtHeading.setGeometry(QtCore.QRect(200, 10, 41, 20))
        self.txtHeading.setText(_fromUtf8(""))
        self.txtHeading.setReadOnly(True)
        self.txtHeading.setObjectName(_fromUtf8("txtHeading"))
        self.txtWaterSpeed = QtGui.QLineEdit(self.frame)
        self.txtWaterSpeed.setEnabled(True)
        self.txtWaterSpeed.setGeometry(QtCore.QRect(200, 100, 41, 20))
        self.txtWaterSpeed.setReadOnly(True)
        self.txtWaterSpeed.setObjectName(_fromUtf8("txtWaterSpeed"))
        self.txtSOG = QtGui.QLineEdit(self.frame)
        self.txtSOG.setEnabled(True)
        self.txtSOG.setGeometry(QtCore.QRect(200, 130, 41, 20))
        self.txtSOG.setReadOnly(True)
        self.txtSOG.setObjectName(_fromUtf8("txtSOG"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 10, 191, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 151, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_6 = QtGui.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(90, 130, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_24 = QtGui.QLabel(self.frame)
        self.label_24.setGeometry(QtCore.QRect(0, 40, 191, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.txtSailHeading = QtGui.QLineEdit(self.frame)
        self.txtSailHeading.setEnabled(True)
        self.txtSailHeading.setGeometry(QtCore.QRect(200, 40, 41, 20))
        self.txtSailHeading.setReadOnly(True)
        self.txtSailHeading.setObjectName(_fromUtf8("txtSailHeading"))
        self.txtDeclination = QtGui.QLineEdit(self.frame)
        self.txtDeclination.setEnabled(True)
        self.txtDeclination.setGeometry(QtCore.QRect(200, 70, 41, 20))
        self.txtDeclination.setReadOnly(True)
        self.txtDeclination.setObjectName(_fromUtf8("txtDeclination"))
        self.label_54 = QtGui.QLabel(self.frame)
        self.label_54.setGeometry(QtCore.QRect(40, 70, 151, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_54.setFont(font)
        self.label_54.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_54.setObjectName(_fromUtf8("label_54"))
        self.lblActuatorStatus_3 = QtGui.QLabel(self.tab)
        self.lblActuatorStatus_3.setGeometry(QtCore.QRect(400, 250, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_3.setFont(font)
        self.lblActuatorStatus_3.setObjectName(_fromUtf8("lblActuatorStatus_3"))
        self.btnStartManual = QtGui.QPushButton(self.tab)
        self.btnStartManual.setGeometry(QtCore.QRect(20, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStartManual.setFont(font)
        self.btnStartManual.setObjectName(_fromUtf8("btnStartManual"))
        self.lblActuatorStatus_2 = QtGui.QLabel(self.tab)
        self.lblActuatorStatus_2.setGeometry(QtCore.QRect(400, 30, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_2.setFont(font)
        self.lblActuatorStatus_2.setObjectName(_fromUtf8("lblActuatorStatus_2"))
        self.txtConnectionStatus = QtGui.QLineEdit(self.tab)
        self.txtConnectionStatus.setGeometry(QtCore.QRect(750, 300, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtConnectionStatus.setFont(font)
        self.txtConnectionStatus.setAutoFillBackground(False)
        self.txtConnectionStatus.setStyleSheet(_fromUtf8("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.txtConnectionStatus.setFrame(False)
        self.txtConnectionStatus.setReadOnly(True)
        self.txtConnectionStatus.setObjectName(_fromUtf8("txtConnectionStatus"))
        self.txtMode = QtGui.QLineEdit(self.tab)
        self.txtMode.setGeometry(QtCore.QRect(750, 330, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txtMode.setFont(font)
        self.txtMode.setAutoFillBackground(False)
        self.txtMode.setStyleSheet(_fromUtf8("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.txtMode.setFrame(False)
        self.txtMode.setReadOnly(True)
        self.txtMode.setObjectName(_fromUtf8("txtMode"))
        self.lblControl = QtGui.QLabel(self.tab)
        self.lblControl.setGeometry(QtCore.QRect(20, 20, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl.setFont(font)
        self.lblControl.setObjectName(_fromUtf8("lblControl"))
        self.frame_3 = QtGui.QFrame(self.tab)
        self.frame_3.setGeometry(QtCore.QRect(750, 80, 201, 161))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.txtBatVoltage = QtGui.QLineEdit(self.frame_3)
        self.txtBatVoltage.setEnabled(True)
        self.txtBatVoltage.setGeometry(QtCore.QRect(130, 72, 61, 20))
        self.txtBatVoltage.setReadOnly(True)
        self.txtBatVoltage.setObjectName(_fromUtf8("txtBatVoltage"))
        self.txtCurrentDraw = QtGui.QLineEdit(self.frame_3)
        self.txtCurrentDraw.setEnabled(True)
        self.txtCurrentDraw.setGeometry(QtCore.QRect(130, 100, 61, 20))
        self.txtCurrentDraw.setReadOnly(True)
        self.txtCurrentDraw.setObjectName(_fromUtf8("txtCurrentDraw"))
        self.label_13 = QtGui.QLabel(self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(32, 72, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.label_14 = QtGui.QLabel(self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(2, 100, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.txtNumSats = QtGui.QLineEdit(self.frame_3)
        self.txtNumSats.setEnabled(True)
        self.txtNumSats.setGeometry(QtCore.QRect(130, 130, 61, 20))
        self.txtNumSats.setReadOnly(True)
        self.txtNumSats.setObjectName(_fromUtf8("txtNumSats"))
        self.label_35 = QtGui.QLabel(self.frame_3)
        self.label_35.setGeometry(QtCore.QRect(0, 130, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.label_37 = QtGui.QLabel(self.frame_3)
        self.label_37.setGeometry(QtCore.QRect(0, 40, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.txtPower = QtGui.QLineEdit(self.frame_3)
        self.txtPower.setEnabled(True)
        self.txtPower.setGeometry(QtCore.QRect(130, 40, 61, 20))
        self.txtPower.setText(_fromUtf8(""))
        self.txtPower.setReadOnly(True)
        self.txtPower.setObjectName(_fromUtf8("txtPower"))
        self.label_38 = QtGui.QLabel(self.frame_3)
        self.label_38.setGeometry(QtCore.QRect(0, 10, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.txtBatRemaining = QtGui.QLineEdit(self.frame_3)
        self.txtBatRemaining.setEnabled(True)
        self.txtBatRemaining.setGeometry(QtCore.QRect(130, 10, 61, 20))
        self.txtBatRemaining.setText(_fromUtf8(""))
        self.txtBatRemaining.setReadOnly(True)
        self.txtBatRemaining.setObjectName(_fromUtf8("txtBatRemaining"))
        self.btnDisableManual = QtGui.QPushButton(self.tab)
        self.btnDisableManual.setGeometry(QtCore.QRect(20, 70, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnDisableManual.setFont(font)
        self.btnDisableManual.setObjectName(_fromUtf8("btnDisableManual"))
        self.frame_2 = QtGui.QFrame(self.tab)
        self.frame_2.setGeometry(QtCore.QRect(390, 290, 251, 301))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.txtWindTrue = QtGui.QLineEdit(self.frame_2)
        self.txtWindTrue.setEnabled(True)
        self.txtWindTrue.setGeometry(QtCore.QRect(180, 10, 61, 20))
        self.txtWindTrue.setText(_fromUtf8(""))
        self.txtWindTrue.setReadOnly(True)
        self.txtWindTrue.setObjectName(_fromUtf8("txtWindTrue"))
        self.txtTrueWindSpeed = QtGui.QLineEdit(self.frame_2)
        self.txtTrueWindSpeed.setEnabled(True)
        self.txtTrueWindSpeed.setGeometry(QtCore.QRect(180, 40, 61, 20))
        self.txtTrueWindSpeed.setReadOnly(True)
        self.txtTrueWindSpeed.setObjectName(_fromUtf8("txtTrueWindSpeed"))
        self.txtDepth = QtGui.QLineEdit(self.frame_2)
        self.txtDepth.setEnabled(True)
        self.txtDepth.setGeometry(QtCore.QRect(180, 130, 61, 20))
        self.txtDepth.setReadOnly(True)
        self.txtDepth.setObjectName(_fromUtf8("txtDepth"))
        self.label_10 = QtGui.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(40, 10, 131, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_11 = QtGui.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(0, 40, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_12 = QtGui.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(80, 130, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.label_25 = QtGui.QLabel(self.frame_2)
        self.label_25.setGeometry(QtCore.QRect(0, 160, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.txtAirTemp = QtGui.QLineEdit(self.frame_2)
        self.txtAirTemp.setEnabled(True)
        self.txtAirTemp.setGeometry(QtCore.QRect(180, 160, 61, 20))
        self.txtAirTemp.setReadOnly(True)
        self.txtAirTemp.setObjectName(_fromUtf8("txtAirTemp"))
        self.txtHumid = QtGui.QLineEdit(self.frame_2)
        self.txtHumid.setEnabled(True)
        self.txtHumid.setGeometry(QtCore.QRect(180, 220, 61, 20))
        self.txtHumid.setReadOnly(True)
        self.txtHumid.setObjectName(_fromUtf8("txtHumid"))
        self.txtPres = QtGui.QLineEdit(self.frame_2)
        self.txtPres.setEnabled(True)
        self.txtPres.setGeometry(QtCore.QRect(180, 250, 61, 20))
        self.txtPres.setReadOnly(True)
        self.txtPres.setObjectName(_fromUtf8("txtPres"))
        self.label_26 = QtGui.QLabel(self.frame_2)
        self.label_26.setGeometry(QtCore.QRect(60, 220, 111, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.label_27 = QtGui.QLabel(self.frame_2)
        self.label_27.setGeometry(QtCore.QRect(10, 250, 161, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_55 = QtGui.QLabel(self.frame_2)
        self.label_55.setGeometry(QtCore.QRect(0, 70, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_55.setFont(font)
        self.label_55.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_55.setObjectName(_fromUtf8("label_55"))
        self.txtWindApp = QtGui.QLineEdit(self.frame_2)
        self.txtWindApp.setEnabled(True)
        self.txtWindApp.setGeometry(QtCore.QRect(180, 70, 61, 20))
        self.txtWindApp.setText(_fromUtf8(""))
        self.txtWindApp.setReadOnly(True)
        self.txtWindApp.setObjectName(_fromUtf8("txtWindApp"))
        self.txtApptWindSpeed = QtGui.QLineEdit(self.frame_2)
        self.txtApptWindSpeed.setEnabled(True)
        self.txtApptWindSpeed.setGeometry(QtCore.QRect(180, 100, 61, 20))
        self.txtApptWindSpeed.setReadOnly(True)
        self.txtApptWindSpeed.setObjectName(_fromUtf8("txtApptWindSpeed"))
        self.label_56 = QtGui.QLabel(self.frame_2)
        self.label_56.setGeometry(QtCore.QRect(0, 100, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_56.setFont(font)
        self.label_56.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_56.setObjectName(_fromUtf8("label_56"))
        self.txtWaterTemp = QtGui.QLineEdit(self.frame_2)
        self.txtWaterTemp.setEnabled(True)
        self.txtWaterTemp.setGeometry(QtCore.QRect(180, 190, 61, 20))
        self.txtWaterTemp.setReadOnly(True)
        self.txtWaterTemp.setObjectName(_fromUtf8("txtWaterTemp"))
        self.label_28 = QtGui.QLabel(self.frame_2)
        self.label_28.setGeometry(QtCore.QRect(0, 190, 171, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.lblActuatorStatus_5 = QtGui.QLabel(self.tab)
        self.lblActuatorStatus_5.setGeometry(QtCore.QRect(750, 250, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_5.setFont(font)
        self.lblActuatorStatus_5.setObjectName(_fromUtf8("lblActuatorStatus_5"))
        self.lblActuatorStatus_4 = QtGui.QLabel(self.tab)
        self.lblActuatorStatus_4.setGeometry(QtCore.QRect(750, 20, 191, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_4.setFont(font)
        self.lblActuatorStatus_4.setObjectName(_fromUtf8("lblActuatorStatus_4"))
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setGeometry(QtCore.QRect(20, 190, 151, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.layoutWidget_2 = QtGui.QWidget(self.tab)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 350, 211, 41))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtDesSail = QtGui.QLineEdit(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesSail.sizePolicy().hasHeightForWidth())
        self.txtDesSail.setSizePolicy(sizePolicy)
        self.txtDesSail.setObjectName(_fromUtf8("txtDesSail"))
        self.horizontalLayout_2.addWidget(self.txtDesSail)
        self.btnDesSail = QtGui.QPushButton(self.layoutWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesSail.sizePolicy().hasHeightForWidth())
        self.btnDesSail.setSizePolicy(sizePolicy)
        self.btnDesSail.setStyleSheet(_fromUtf8(""))
        self.btnDesSail.setObjectName(_fromUtf8("btnDesSail"))
        self.horizontalLayout_2.addWidget(self.btnDesSail)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setGeometry(QtCore.QRect(20, 330, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab)
        self.layoutWidget_3.setGeometry(QtCore.QRect(30, 280, 211, 41))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.txtDesROT = QtGui.QLineEdit(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesROT.sizePolicy().hasHeightForWidth())
        self.txtDesROT.setSizePolicy(sizePolicy)
        self.txtDesROT.setObjectName(_fromUtf8("txtDesROT"))
        self.horizontalLayout_3.addWidget(self.txtDesROT)
        self.btnDesROT = QtGui.QPushButton(self.layoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesROT.sizePolicy().hasHeightForWidth())
        self.btnDesROT.setSizePolicy(sizePolicy)
        self.btnDesROT.setStyleSheet(_fromUtf8(""))
        self.btnDesROT.setObjectName(_fromUtf8("btnDesROT"))
        self.horizontalLayout_3.addWidget(self.btnDesROT)
        self.label_17 = QtGui.QLabel(self.tab)
        self.label_17.setGeometry(QtCore.QRect(10, 260, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.layoutWidget = QtGui.QWidget(self.tab)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 210, 211, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.txtDesHeading = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesHeading.sizePolicy().hasHeightForWidth())
        self.txtDesHeading.setSizePolicy(sizePolicy)
        self.txtDesHeading.setObjectName(_fromUtf8("txtDesHeading"))
        self.horizontalLayout.addWidget(self.txtDesHeading)
        self.btnDesHeading = QtGui.QPushButton(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesHeading.sizePolicy().hasHeightForWidth())
        self.btnDesHeading.setSizePolicy(sizePolicy)
        self.btnDesHeading.setStyleSheet(_fromUtf8(""))
        self.btnDesHeading.setObjectName(_fromUtf8("btnDesHeading"))
        self.horizontalLayout.addWidget(self.btnDesHeading)
        self.txt0x80Status = QtGui.QLineEdit(self.tab)
        self.txt0x80Status.setGeometry(QtCore.QRect(750, 380, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt0x80Status.setFont(font)
        self.txt0x80Status.setAutoFillBackground(False)
        self.txt0x80Status.setStyleSheet(_fromUtf8("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.txt0x80Status.setFrame(False)
        self.txt0x80Status.setReadOnly(True)
        self.txt0x80Status.setObjectName(_fromUtf8("txt0x80Status"))
        self.txt0x81Status = QtGui.QLineEdit(self.tab)
        self.txt0x81Status.setGeometry(QtCore.QRect(750, 410, 201, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.txt0x81Status.setFont(font)
        self.txt0x81Status.setAutoFillBackground(False)
        self.txt0x81Status.setStyleSheet(_fromUtf8("background-color: rgb(150, 0, 0);\n"
"color: rgb(255, 255, 255);"))
        self.txt0x81Status.setFrame(False)
        self.txt0x81Status.setReadOnly(True)
        self.txt0x81Status.setObjectName(_fromUtf8("txt0x81Status"))
        self.btnPropOn = QtGui.QPushButton(self.tab)
        self.btnPropOn.setGeometry(QtCore.QRect(20, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPropOn.setFont(font)
        self.btnPropOn.setObjectName(_fromUtf8("btnPropOn"))
        self.btnPropOff = QtGui.QPushButton(self.tab)
        self.btnPropOff.setGeometry(QtCore.QRect(20, 110, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnPropOff.setFont(font)
        self.btnPropOff.setObjectName(_fromUtf8("btnPropOff"))
        self.label_36 = QtGui.QLabel(self.tab)
        self.label_36.setGeometry(QtCore.QRect(750, 360, 121, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.label_18 = QtGui.QLabel(self.tab)
        self.label_18.setGeometry(QtCore.QRect(20, 400, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.layoutWidget_4 = QtGui.QWidget(self.tab)
        self.layoutWidget_4.setGeometry(QtCore.QRect(30, 420, 211, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.layoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.txtDesSailAngle = QtGui.QLineEdit(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDesSailAngle.sizePolicy().hasHeightForWidth())
        self.txtDesSailAngle.setSizePolicy(sizePolicy)
        self.txtDesSailAngle.setObjectName(_fromUtf8("txtDesSailAngle"))
        self.horizontalLayout_4.addWidget(self.txtDesSailAngle)
        self.btnDesSailAngle = QtGui.QPushButton(self.layoutWidget_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDesSailAngle.sizePolicy().hasHeightForWidth())
        self.btnDesSailAngle.setSizePolicy(sizePolicy)
        self.btnDesSailAngle.setStyleSheet(_fromUtf8(""))
        self.btnDesSailAngle.setObjectName(_fromUtf8("btnDesSailAngle"))
        self.horizontalLayout_4.addWidget(self.btnDesSailAngle)
        self.label_19 = QtGui.QLabel(self.tab)
        self.label_19.setGeometry(QtCore.QRect(69, 962, 181, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.txtUTC = QtGui.QLineEdit(self.tab)
        self.txtUTC.setGeometry(QtCore.QRect(40, 540, 221, 31))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtUTC.sizePolicy().hasHeightForWidth())
        self.txtUTC.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtUTC.setFont(font)
        self.txtUTC.setText(_fromUtf8(""))
        self.txtUTC.setObjectName(_fromUtf8("txtUTC"))
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setGeometry(QtCore.QRect(40, 510, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans Mono"))
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.txtComments = QtGui.QTextEdit(self.tab)
        self.txtComments.setGeometry(QtCore.QRect(40, 610, 271, 70))
        self.txtComments.setObjectName(_fromUtf8("txtComments"))
        self.label_21 = QtGui.QLabel(self.tab)
        self.label_21.setGeometry(QtCore.QRect(40, 580, 91, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("DejaVu Sans Mono"))
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setGeometry(QtCore.QRect(750, 490, 251, 100))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.txtState = QtGui.QLineEdit(self.frame_5)
        self.txtState.setEnabled(True)
        self.txtState.setGeometry(QtCore.QRect(90, 20, 141, 21))
        self.txtState.setReadOnly(True)
        self.txtState.setObjectName(_fromUtf8("txtState"))
        self.txtSubstate = QtGui.QLineEdit(self.frame_5)
        self.txtSubstate.setEnabled(True)
        self.txtSubstate.setGeometry(QtCore.QRect(90, 60, 141, 21))
        self.txtSubstate.setReadOnly(True)
        self.txtSubstate.setObjectName(_fromUtf8("txtSubstate"))
        self.label_22 = QtGui.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(-20, 20, 101, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.label_23 = QtGui.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(-50, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.lblActuatorStatus_6 = QtGui.QLabel(self.tab)
        self.lblActuatorStatus_6.setGeometry(QtCore.QRect(750, 440, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblActuatorStatus_6.setFont(font)
        self.lblActuatorStatus_6.setObjectName(_fromUtf8("lblActuatorStatus_6"))
        self.btnAutoSail = QtGui.QPushButton(self.tab)
        self.btnAutoSail.setGeometry(QtCore.QRect(20, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAutoSail.setFont(font)
        self.btnAutoSail.setObjectName(_fromUtf8("btnAutoSail"))
        self.btnAutoSailDisable = QtGui.QPushButton(self.tab)
        self.btnAutoSailDisable.setGeometry(QtCore.QRect(20, 150, 171, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAutoSailDisable.setFont(font)
        self.btnAutoSailDisable.setObjectName(_fromUtf8("btnAutoSailDisable"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setEnabled(False)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.lblControl_2 = QtGui.QLabel(self.tab_2)
        self.lblControl_2.setGeometry(QtCore.QRect(20, 20, 251, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl_2.setFont(font)
        self.lblControl_2.setObjectName(_fromUtf8("lblControl_2"))
        self.frame_4 = QtGui.QFrame(self.tab_2)
        self.frame_4.setGeometry(QtCore.QRect(20, 70, 166, 100))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.txtRudderSpeed = QtGui.QLineEdit(self.frame_4)
        self.txtRudderSpeed.setEnabled(False)
        self.txtRudderSpeed.setGeometry(QtCore.QRect(90, 12, 61, 20))
        self.txtRudderSpeed.setReadOnly(True)
        self.txtRudderSpeed.setObjectName(_fromUtf8("txtRudderSpeed"))
        self.txtSailSpeed = QtGui.QLineEdit(self.frame_4)
        self.txtSailSpeed.setEnabled(False)
        self.txtSailSpeed.setGeometry(QtCore.QRect(90, 40, 61, 20))
        self.txtSailSpeed.setReadOnly(True)
        self.txtSailSpeed.setObjectName(_fromUtf8("txtSailSpeed"))
        self.txtPropSpeed = QtGui.QLineEdit(self.frame_4)
        self.txtPropSpeed.setEnabled(False)
        self.txtPropSpeed.setGeometry(QtCore.QRect(90, 68, 61, 20))
        self.txtPropSpeed.setReadOnly(True)
        self.txtPropSpeed.setObjectName(_fromUtf8("txtPropSpeed"))
        self.label_7 = QtGui.QLabel(self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(12, 12, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(2, 40, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(12, 68, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Monospace"))
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.btnSetDerivative = QtGui.QPushButton(self.tab_2)
        self.btnSetDerivative.setGeometry(QtCore.QRect(150, 360, 41, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetDerivative.sizePolicy().hasHeightForWidth())
        self.btnSetDerivative.setSizePolicy(sizePolicy)
        self.btnSetDerivative.setStyleSheet(_fromUtf8(""))
        self.btnSetDerivative.setObjectName(_fromUtf8("btnSetDerivative"))
        self.txtI = QtGui.QLineEdit(self.tab_2)
        self.txtI.setEnabled(False)
        self.txtI.setGeometry(QtCore.QRect(50, 330, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtI.setFont(font)
        self.txtI.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtI.setReadOnly(True)
        self.txtI.setObjectName(_fromUtf8("txtI"))
        self.lblControl_3 = QtGui.QLabel(self.tab_2)
        self.lblControl_3.setGeometry(QtCore.QRect(20, 210, 221, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblControl_3.setFont(font)
        self.lblControl_3.setObjectName(_fromUtf8("lblControl_3"))
        self.btnEnablePIDTuning = QtGui.QPushButton(self.tab_2)
        self.btnEnablePIDTuning.setGeometry(QtCore.QRect(30, 250, 71, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnEnablePIDTuning.setFont(font)
        self.btnEnablePIDTuning.setObjectName(_fromUtf8("btnEnablePIDTuning"))
        self.txtEffort = QtGui.QLineEdit(self.tab_2)
        self.txtEffort.setEnabled(False)
        self.txtEffort.setGeometry(QtCore.QRect(310, 350, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtEffort.setFont(font)
        self.txtEffort.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtEffort.setReadOnly(True)
        self.txtEffort.setObjectName(_fromUtf8("txtEffort"))
        self.txtIInput = QtGui.QLineEdit(self.tab_2)
        self.txtIInput.setGeometry(QtCore.QRect(100, 330, 41, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtIInput.sizePolicy().hasHeightForWidth())
        self.txtIInput.setSizePolicy(sizePolicy)
        self.txtIInput.setObjectName(_fromUtf8("txtIInput"))
        self.txtP = QtGui.QLineEdit(self.tab_2)
        self.txtP.setEnabled(False)
        self.txtP.setGeometry(QtCore.QRect(50, 300, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtP.setFont(font)
        self.txtP.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtP.setReadOnly(True)
        self.txtP.setObjectName(_fromUtf8("txtP"))
        self.txtDInput = QtGui.QLineEdit(self.tab_2)
        self.txtDInput.setGeometry(QtCore.QRect(100, 360, 41, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtDInput.sizePolicy().hasHeightForWidth())
        self.txtDInput.setSizePolicy(sizePolicy)
        self.txtDInput.setObjectName(_fromUtf8("txtDInput"))
        self.lblEffort = QtGui.QLabel(self.tab_2)
        self.lblEffort.setGeometry(QtCore.QRect(210, 400, 111, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblEffort.setFont(font)
        self.lblEffort.setObjectName(_fromUtf8("lblEffort"))
        self.txtROT = QtGui.QLineEdit(self.tab_2)
        self.txtROT.setEnabled(False)
        self.txtROT.setGeometry(QtCore.QRect(310, 350, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtROT.setFont(font)
        self.txtROT.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtROT.setReadOnly(True)
        self.txtROT.setObjectName(_fromUtf8("txtROT"))
        self.txtPInput = QtGui.QLineEdit(self.tab_2)
        self.txtPInput.setGeometry(QtCore.QRect(100, 300, 41, 20))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPInput.sizePolicy().hasHeightForWidth())
        self.txtPInput.setSizePolicy(sizePolicy)
        self.txtPInput.setObjectName(_fromUtf8("txtPInput"))
        self.txtD = QtGui.QLineEdit(self.tab_2)
        self.txtD.setEnabled(False)
        self.txtD.setGeometry(QtCore.QRect(50, 360, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtD.setFont(font)
        self.txtD.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtD.setReadOnly(True)
        self.txtD.setObjectName(_fromUtf8("txtD"))
        self.lblI = QtGui.QLabel(self.tab_2)
        self.lblI.setGeometry(QtCore.QRect(30, 330, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblI.setFont(font)
        self.lblI.setObjectName(_fromUtf8("lblI"))
        self.lblROT = QtGui.QLabel(self.tab_2)
        self.lblROT.setGeometry(QtCore.QRect(210, 350, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblROT.setFont(font)
        self.lblROT.setObjectName(_fromUtf8("lblROT"))
        self.lblD = QtGui.QLabel(self.tab_2)
        self.lblD.setGeometry(QtCore.QRect(30, 360, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblD.setFont(font)
        self.lblD.setObjectName(_fromUtf8("lblD"))
        self.txtError = QtGui.QLineEdit(self.tab_2)
        self.txtError.setEnabled(False)
        self.txtError.setGeometry(QtCore.QRect(310, 320, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.txtError.setFont(font)
        self.txtError.setStyleSheet(_fromUtf8("border: 1px solid transparent;\n"
"background: transparent;"))
        self.txtError.setReadOnly(True)
        self.txtError.setObjectName(_fromUtf8("txtError"))
        self.lblP = QtGui.QLabel(self.tab_2)
        self.lblP.setGeometry(QtCore.QRect(30, 300, 16, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblP.setFont(font)
        self.lblP.setObjectName(_fromUtf8("lblP"))
        self.lblError = QtGui.QLabel(self.tab_2)
        self.lblError.setGeometry(QtCore.QRect(210, 370, 91, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.lblError.setFont(font)
        self.lblError.setObjectName(_fromUtf8("lblError"))
        self.btnSetProportional = QtGui.QPushButton(self.tab_2)
        self.btnSetProportional.setGeometry(QtCore.QRect(150, 299, 41, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetProportional.sizePolicy().hasHeightForWidth())
        self.btnSetProportional.setSizePolicy(sizePolicy)
        self.btnSetProportional.setStyleSheet(_fromUtf8(""))
        self.btnSetProportional.setObjectName(_fromUtf8("btnSetProportional"))
        self.btnSetIntegral = QtGui.QPushButton(self.tab_2)
        self.btnSetIntegral.setGeometry(QtCore.QRect(150, 330, 41, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnSetIntegral.sizePolicy().hasHeightForWidth())
        self.btnSetIntegral.setSizePolicy(sizePolicy)
        self.btnSetIntegral.setStyleSheet(_fromUtf8(""))
        self.btnSetIntegral.setObjectName(_fromUtf8("btnSetIntegral"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.btnStop = QtGui.QPushButton(self.centralwidget)
        self.btnStop.setEnabled(True)
        self.btnStop.setGeometry(QtCore.QRect(10, 770, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btnStop.setFont(font)
        self.btnStop.setStyleSheet(_fromUtf8("QPushButton {color: red;}\n"
""))
        self.btnStop.setObjectName(_fromUtf8("btnStop"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Boat Heading true (deg):", None))
        self.label_2.setText(_translate("MainWindow", "Water speed (km/h):", None))
        self.label_6.setText(_translate("MainWindow", "SOG (km/h):", None))
        self.label_24.setText(_translate("MainWindow", "Sail Heading true (deg):", None))
        self.label_54.setText(_translate("MainWindow", "Declination (deg):", None))
        self.lblActuatorStatus_3.setText(_translate("MainWindow", "Environment", None))
        self.btnStartManual.setText(_translate("MainWindow", "Enable manual", None))
        self.lblActuatorStatus_2.setText(_translate("MainWindow", "NAV Info", None))
        self.txtConnectionStatus.setText(_translate("MainWindow", "DISCONNECTED", None))
        self.txtMode.setText(_translate("MainWindow", "MANUAL DISABLED", None))
        self.lblControl.setText(_translate("MainWindow", "Control", None))
        self.label_13.setText(_translate("MainWindow", "Bat Voltage", None))
        self.label_14.setText(_translate("MainWindow", "Current draw[A]", None))
        self.label_35.setText(_translate("MainWindow", "Sats in view", None))
        self.label_37.setText(_translate("MainWindow", "Power usage[W]", None))
        self.label_38.setText(_translate("MainWindow", "Power level (%)", None))
        self.btnDisableManual.setText(_translate("MainWindow", "Disable manual", None))
        self.label_10.setText(_translate("MainWindow", "True wind(deg):", None))
        self.label_11.setText(_translate("MainWindow", "True wind speed(km/h):", None))
        self.label_12.setText(_translate("MainWindow", "Depth (m):", None))
        self.label_25.setText(_translate("MainWindow", "Air Temperature(C):", None))
        self.label_26.setText(_translate("MainWindow", "Humidity (%):", None))
        self.label_27.setText(_translate("MainWindow", "Air Pressure (mbar):", None))
        self.label_55.setText(_translate("MainWindow", "Apparent wind(deg):", None))
        self.label_56.setText(_translate("MainWindow", "Appt wind speed(km/h):", None))
        self.label_28.setText(_translate("MainWindow", "Water Temperature(C):", None))
        self.lblActuatorStatus_5.setText(_translate("MainWindow", "Status", None))
        self.lblActuatorStatus_4.setText(_translate("MainWindow", "Stats", None))
        self.label_15.setText(_translate("MainWindow", "Desired heading:", None))
        self.btnDesSail.setText(_translate("MainWindow", "SET", None))
        self.label_16.setText(_translate("MainWindow", "Desired sail heading:", None))
        self.btnDesROT.setText(_translate("MainWindow", "SET", None))
        self.label_17.setText(_translate("MainWindow", "Desired ROT", None))
        self.btnDesHeading.setText(_translate("MainWindow", "SET", None))
        self.txt0x80Status.setText(_translate("MainWindow", "0x80 No status received", None))
        self.txt0x81Status.setText(_translate("MainWindow", "0x81 No status received", None))
        self.btnPropOn.setText(_translate("MainWindow", "Prop ON", None))
        self.btnPropOff.setText(_translate("MainWindow", "Prop OFF", None))
        self.label_36.setText(_translate("MainWindow", "Roboclaws", None))
        self.label_18.setText(_translate("MainWindow", "Desired sail angle:", None))
        self.btnDesSailAngle.setText(_translate("MainWindow", "SET", None))
        self.label_19.setText(_translate("MainWindow", "Desired sail angle:", None))
        self.label_20.setText(_translate("MainWindow", "UTC Time", None))
        self.label_21.setText(_translate("MainWindow", "Comments", None))
        self.label_22.setText(_translate("MainWindow", "State :", None))
        self.label_23.setText(_translate("MainWindow", "Substate :", None))
        self.lblActuatorStatus_6.setText(_translate("MainWindow", "Boat State", None))
        self.btnAutoSail.setText(_translate("MainWindow", "Auto sail", None))
        self.btnAutoSailDisable.setText(_translate("MainWindow", "Disable auto sail", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Overview", None))
        self.lblControl_2.setText(_translate("MainWindow", "Set actuator speeds", None))
        self.label_7.setText(_translate("MainWindow", "Rudder", None))
        self.label_8.setText(_translate("MainWindow", "Sail", None))
        self.label_9.setText(_translate("MainWindow", "Prop", None))
        self.btnSetDerivative.setText(_translate("MainWindow", "Set", None))
        self.txtI.setText(_translate("MainWindow", "-99", None))
        self.lblControl_3.setText(_translate("MainWindow", "PID tuning", None))
        self.btnEnablePIDTuning.setText(_translate("MainWindow", "Enable", None))
        self.txtEffort.setText(_translate("MainWindow", "-99", None))
        self.txtP.setText(_translate("MainWindow", "-99", None))
        self.lblEffort.setText(_translate("MainWindow", "Effort", None))
        self.txtROT.setText(_translate("MainWindow", "-99", None))
        self.txtD.setText(_translate("MainWindow", "-99", None))
        self.lblI.setText(_translate("MainWindow", "I", None))
        self.lblROT.setText(_translate("MainWindow", "ROT", None))
        self.lblD.setText(_translate("MainWindow", "D", None))
        self.txtError.setText(_translate("MainWindow", "-99", None))
        self.lblP.setText(_translate("MainWindow", "P", None))
        self.lblError.setText(_translate("MainWindow", "Error", None))
        self.btnSetProportional.setText(_translate("MainWindow", "Set", None))
        self.btnSetIntegral.setText(_translate("MainWindow", "Set", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Settings", None))
        self.btnStop.setText(_translate("MainWindow", "STOP", None))

